language: android
jdk: oraclejdk8

env:
  global:
    - ANDROID_API_LEVEL=25
    - ANDROID_BUILD_TOOLS_VERSION=25.0.3
    - TRAVIS_SECURE_ENV_VARS=true

android:
  components:
    - tools
    - platform-tools
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION

    # system images
    - sys-img-armeabi-v7a-android-$ANDROID_API_LEVEL
    - sys-img-x86-android-$ANDROID_API_LEVEL
    - sys-img-armeabi-v7a-android-22
    - sys-img-armeabi-v7a-android-19
    - sys-img-armeabi-v7a-android-17

    # extras
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - extra-android-support

    # addons
    - addon-google_apis-google-$ANDROID_API_LEVEL

    # The SDK version used to compile your project
    - android-$ANDROID_API_LEVEL

licenses:
  - '.+'

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

script:
    - ./gradlew test
#    - ./gradlew build    
#    - ./gradlew clean
#    - ./gradlew test
#    - ./gradlew build connectedCheck


before_install:
 - chmod +x gradlew
